### ISSUE TITLE
[datasets] Add data pipelines 

### ISSUE THREAD

**Issue by dataJSA** [pyronear/pyro-risks#19]
Hello everybody 🎄 

As said earlier we need to put together the data pipelines ! 

Currently what we have is the different training datasets attached to the release on Github. 
The overall goal is to develop two data pipelines:
 
- **a scoring data pipeline**: data from day D to D-7
- **a training data pipeline** : TBD

As the first release model will be exposed for demonstration purposes, I think we can focus on the **scoring data pipeline** for now. 

For the scoring data pipelines what I propose is to wrap the *get_** functions* (raw FWI and ERA5 datasets) into a **command line app** and to use a **makefile** for the bash commands.

I will start working on this, @frgfm @miltminz @GHCamille @chloeskt let me know what you think !

**Comment by frgfm** [comment]
Thanks for opening up the discussion!
Could you elaborate on what you have in mind for the CLI/makefile?

Perhaps I don't understand this well, but if the scoring pipeline is about producing the predictions, then we can only put up a proper  "models" submodule?
Then we'll just need to add the model checkpoint to a release and add a `pretrained` arg to the model function that would load up the trained model.

Wrapping everything with an exposed app would be another matter that we can deal using fastapi or django for instance!

Let me know if I misunderstood!

**Comment by dataJSA** [comment]
Yes,

I just drew of the production pipeline
 
![image](https://user-images.githubusercontent.com/45068597/101475939-49e5e400-394d-11eb-8bb5-319a310519f0.png)

I do agree with the steps you are proposing however for producing the daily predictions we need the pretrained model and to download each day the required features from the last 7 days. This is why I was mentioning a scoring data pipeline 

What we have produced so far is 

- functions in the `datasets/utils` module for retrieving the datasets.
- a module for each datatsets (`datasets/ERA5`) with a class that is initialized by passing the dataset file location (with the github release as a fall back) and does the preprocessing  
- scripts that merge the different datasets 
- training pipeline (coming soon) 

Rather than doing all the step in one scripts I was thinking of each of those steps as a standalone script. 
Thus the need for a Makefile for gluing the script together. However going for a python script first seems reasonable !

@chloeskt and @miltminz let me know I missed anything
