### ISSUE TITLE
[web server] Exposing the model inference part of the lib

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-risks#20]
Currently, the package can help a python user within a shell. For proper service separation, it would be good that the risk scoring is on a different resource than the API or the platform, which means that it needs to be able to communicate.

We should then wrap this in a web server (fastapi for instance) to expose correctly the model. More specifically, this would ideally require the following:

- [ ] a web-app built with FastAPI
- [ ] a dockerfile to have requestable container
- [ ] setting up heroku deployment

**Comment by chloeskt** [comment]
Hi @frgfm thank you for this issue 😃 
I agree ! To be sure, the only feature of this web app (for now, we can/will add more later) is:
- give the risk score for a given day on all French departements ?

**Comment by frgfm** [comment]
@chloeskt correct!
