### ISSUE TITLE
[cache] Added a cache mechanism for file downloading

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-risks#21]
Currently, whenever a big file download is required, the actual download is done no matter how many times the operation was performed over the day. For efficiency purposes, we would need to set a cache mechanism:
- [x] dummy cache: we can create a `.cache` directory where each new file will be saved for the next time a download is called. For that to work, we need to think about a proper naming convention of the file so that we can retrieve it from the cache. Calling the operation will first check in the `.cache` directory if the data is already there before attempting to DL it. (#27)
- [ ] advanced cache: we could set an actual cache container (redis for instance) that would be used as a full cache available to the score prediction container. The cached file will already be loaded as binary streams.

Any feedback is welcome!
cc @dataJSA

**Comment by dataJSA** [comment]
Hi @frgfm thanks for the issue ! 

The dummy cache description seems clear to me, I will work on that and then give a try at building an advance cache mechanism with redis.

I am pretty sure that when I will start implementing I will have some questions that we can discuss here

**Comment by frgfm** [comment]
@dataJSA sure, feel free ti ping me if you need help so that we can manage to get this working shortly :ok_hand:

**Comment by frgfm** [comment]
Perhaps we should consider simply putting the `.cache` folder in a more appropriate location similarly to what deep learning framework do? Many python project place it in `.cache/python_lib` where `python_lib` is the project name.

The redis option is good for production, but for local usage, I'm starting to think that it's not really something we want. What do you think?

**Comment by dataJSA** [comment]
Yes you are right for the cache folder its cleaner ! 

Concerning the use of redis for caching the datasets in production I wonder if it still the best solution. 
I just opened the issue #37 where I try to present our current workflow and how we could orchestrate it in production. 

The idea being that if we have storage and a compute instance we can 
- download the dataset once a day
- clean it and store it 
- do some batch prediction
- serve the predicted datasets

In this scenario I am not sure if we still would need redis, let me know what you think

**Comment by frgfm** [comment]
I agree, the things we would be caching are both heavy and require access for 24 hours at least. No need for a fancy caching system here

**Comment by dataJSA** [comment]
> Many python project place it in `.cache/python_lib` where `python_lib` is the project name.

I took a look at the download default destination for keras, pytorch and sklearn.
- In pytorch the datasets are by default downloaded were the program runs this is where the `.cache` file is currently created. 
- In keras and sklearn they broadly create an `~/.python_lib/datasets`

Just to be sure I understood correctly you were suggesting to create the cache directory in the user home directory and go with `~/.python_lib/.cache` ?

**Comment by frgfm** [comment]
The opposite, I was suggesting `~/.cache/python_lib` ;)
