### ISSUE TITLE
[predict]  Predict module refactoring

### ISSUE THREAD

**Issue by dataJSA** [pyronear/pyro-risks#37]
Right now, the `predict.py` module contains the `PyroRisk` class with the `predict` method that is used during API calls. The current prediction workflow is the following:

- download and merge daily inputs (J-1, J-3, J-7)  (`get_fwi_data_for_predict`, `get_data_era5t_for_predict`)
- preprocessed the dataset (previous preprocessing functions)
- score the new instances

This entire workflow is rolled out at prediction time. It was great for getting going especially because allows us to not persist the daily datasets but I suspect it may have caused some of the timeouts that have been experienced. 

Now that we have started discussing about the target infrastructure, it could be great to refactor this module with the production workflow in mind.

# Design 

I think that rather than orchestrating each steps within a script or main functions **we could use an orchestration framework like airflow to define and execute the workflows**.

Since the scores are needed on a daily basis we could follow a workflow similar to the steps proposed bellow: 

- download raw data from the platform
- Transform the raw dataset into clean data
- Preprocess and score the incoming clean dataset (cf training pipeline see issue #)

The objectif being that thus we could replace the predict function within the API with a function that just reads and serves the score when called.

# Implementation details

- Refactor predict function to ensure compatibility with the trained pipelines
- decouple downloading and cleaning of the data from prediction by storing data in cache or target directory and implementing load step within

Let me know what you think guys !

**Comment by GHCamille** [comment]
Yep, so I guess we will handle this issue after we're done with the pipelines, right ? 
Also about Airflow, do we wait to know what's our CSP to know which orchestration tool will be the best fitted ? 
Idk if it's relevant here, but I also heard a lot about dagster instead of airflow, though I've never used it, do you know about it/have you tried it ?

**Comment by dataJSA** [comment]
Yes exactly ! Concerning the orchestration tool we will I think we need to factor in a few things especially if we need to sync the tools we use on other projects. 

I think we should open the discussion on that subject and benchmark tools with the whole team. It could be great to factor in the orchestration capabilities of the different CSP before  choosing one, even if we end up managing the orchestration ourselves.

I didn't know dagster but I quickly looked at it, it seems really nice !
