### ISSUE TITLE
[ci] Enforce type hinting 

### ISSUE THREAD

**Issue by dataJSA** [pyronear/pyro-risks#39]
## Motivation

We adopted type hinting, however we never enforced checks to ensure this convention was respected !  

## 🚀 Change

We should enforce type hinting, this would require:

- [x] Ensuring that all the functions are correctly typed
- [x] Implementing checks by defining a `type-hints` job in the `pyro-risks/.github/workflows/main.yml` using the `mypy.ini` file at the root of the repository

**Comment by GHCamille** [comment]
Happy to help you with this once I'm done with the unittests !

**Comment by dataJSA** [comment]
Thanks @GHCamille!

**Comment by GHCamille** [comment]
@dataJSA I made some researches about using mypy.ini to implement automatic checks, but I'm not sure I understand - Should I implement checks in a yml file ? mypy.ini file ? I'm a bit lost sorry 😅
