### ISSUE TITLE
[datasets] Add seasonal forecast daily dataset

### ISSUE THREAD

**Issue by jsakv** [pyronear/pyro-risks#44]
## Motivation

As discussed in the issue #31 , the ERA5T features are only available on day D+5. To account for production constraints we could explore other datasets.

## 🚀 Feature

Add [Seasonal forecast daily data on single levels datasets](https://cds.climate.copernicus.eu/cdsapp#!/dataset/seasonal-original-single-levels?tab=overview), to the pyro_risks package 

## Design Proposal

The implementation should follow the implementation of the `datasets/ERA5.py` module, 
we should first explore the datasets and compare it to the ERA5T dataset, then implement the related class.

Let me know what you think!

**Comment by GHCamille** [comment]
Regarding this dataset, I actually tried but cannot get data fresher than 1 month old, did you succeed ?

**Comment by dataJSA** [comment]
Nope, I didn't check this dataset myself! I was so hopeful

**Comment by GHCamille** [comment]
Just found some data sources we can check for this PR !

=> https://climate.copernicus.eu/discover-last-years-climate-newly-released-european-state-climate-2020 

In the last figure they compared their ERA-5 temperature levels with other datasources that we haven't checked: 

- Berkeley Earth
- HadCRUT5
- GISTEMPv4
- JRA-55

Let's investigate.
