### ISSUE TITLE
[models] Improve classification pipelines (resampling, tuning)

### ISSUE THREAD

**Issue by jsakv** [pyronear/pyro-risks#46]
## Motivation

Currently, the XGBoost and Random Forest training pipelines defined within the `models/pipelines.py` module only implements **preprocessing and scoring steps**. Given that our **training dataset is imbalanced, resampling is likely to improve performance**. Moreover, the hyperparameters selected are not relevant to the current pipelines.

## ✨ Change

In order to improve the scoring pipeline performance, we should implement and test various resampling strategies. This would require to:

- [ ] Test multiple sequences of preprocessing, resampling and modeling steps.
- [ ] Select optimal hyperparameters
- [ ] Account for production constraints. As discussed in the issue #31, the dataset features are only available on day D+5, so we would need to shift the target by 5 days.
- [ ] (Optional) Add new preprocessing steps

## Additional context

- The dataset used for modeling is available with `MergedEraFwiViirs()` the documentation of the different features is available here [https://pyronear.org/pyro-risks/](https://pyronear.org/pyro-risks/)
- It's better to split the dataset using the `TEST_SIZE` and  `RANDOM_STATE` values in the `config` module: 
- This article demonstrates how to set up a pipeline with imbalanced-learn [SMOTE for Imbalanced Classification with Python](https://machinelearningmastery.com/smote-oversampling-for-imbalanced-classification/)
- For avoiding skewing the training datasets (less accurate imputation of missing values) is better to define pipelines steps in the following order: `preprocessing >> upsampling >> modeling`
- Hyperparameter tuning can be long for caching the steps that are not modify during the search which speeds up hyper-parameters tuning

    ```bash
    from joblib import Memory
    from imblearn.pipeline import Pipeline

    location = './cachedir'
    memory = Memory(location, verbose=0)

    pipe = Pipeline([('step', Step)],
                    memory=memory)
    ```

**Comment by GHCamille** [comment]
###  ✨ Resampling situation assessement ✨

... and SMOTE first try



Current situation : 

<img width="676" alt="Capture d’écran 2021-05-04 à 19 39 56" src="https://user-images.githubusercontent.com/33114679/117046461-02ebf700-ad11-11eb-8eda-287773465e0e.png">


With SMOTE only (no additional tuning) :

<img width="691" alt="Capture d’écran 2021-05-04 à 19 40 02" src="https://user-images.githubusercontent.com/33114679/117046438-fe274300-ad10-11eb-9032-77286123a073.png">


Results : 

![smote_no_ratio](https://user-images.githubusercontent.com/33114679/117045150-7c82e580-ad0f-11eb-987d-98a9b82beaab.png)


With SMOTE tuned with 3x ratio:

<img width="682" alt="Capture d’écran 2021-05-04 à 19 40 06" src="https://user-images.githubusercontent.com/33114679/117046416-f5367180-ad10-11eb-84c0-ec6bafb5b169.png">


Results : 

![smote_ratio_3](https://user-images.githubusercontent.com/33114679/117045391-beac2700-ad0f-11eb-9cda-a6c1db4af9f1.png)

With SMOTE tuned with 5x ratio:

<img width="658" alt="Capture d’écran 2021-05-04 à 19 40 09" src="https://user-images.githubusercontent.com/33114679/117046396-efd92700-ad10-11eb-8801-68262e0155b3.png">

Results : 

![smote_ratio_5_dataset](https://user-images.githubusercontent.com/33114679/117045523-e3a09a00-ad0f-11eb-959a-48bf0d128224.png)

###  Conclusion

=> For now, the best SMOTE configuration is without any ratio tuning.

=> Let's see if it's better if we try a combination of too much over sampling + under sampling : https://www.analyticsvidhya.com/blog/2020/10/overcoming-class-imbalance-using-smote-techniques/

**Comment by dataJSA** [comment]
Thanks, @GHCamille that's a great improvement of the recall from the baseline pipelines! I am curious are you training the Random Forest classifier or the XGBoost classifier?

Also, it might help to play a little bit more with the class weights hyperparameters of the different classifiers for rebalancing the class during the sampling.
- The `RandomForestClassifier` has already the `class_weight` parameter set to `"balanced"`
- The `XGBoostClassifier`has the parameter `scale_pos_weight` that  we should set around this value `sum(negative instances) / sum(positive instances)`
 
We will see if it improves the performances a bit!

**Comment by GHCamille** [comment]
Hey, thanks ! Only RandomForest. I cannot run XGBoost on my computer for now. 

Ok thank you for this info ! 👌
