### ISSUE TITLE
[datasets] Narrow down score level of aggregation

### ISSUE THREAD

**Issue by GHCamille** [pyronear/pyro-risks#58]
## Motivation

The department level is too broad, as there are several SDIS by department. 

We have to find a smaller level of aggregation. 

## 🚀 Feature

Improve PyroRisk score's geospatial accuracy .

## Design Proposal

📍 Aggregate data at the station level.

## Alternatives

I see one alternative :
1. ​Find/Create a map of SDIS's areas of coverage.
2. Turn it into a GeoJSON.
3. Aggregate score on SDIS level.

___________________

I don't think this issue is a priority for now, however we have to keep in mind that we eventually want to get there.

Let me know what you think 🌰

**Comment by dataJSA** [comment]
Thanks for raising this issue @GHCamille!

I totally agree with you, I understand that your second proposal would require more work but it could provide a huge improvement for SDIS if we could narrow down the dataset resolution and score on their specific areas!
